### ISSUE TITLE
Resource: Project Memberships

### ISSUE THREAD

**Issue by berfarah** [berfarah/pivotal.cr#3]
## Sample
```json
[{
   "created_at": "2016-10-18T12:00:00Z",
   "id": 16200,
   "kind": "project_membership",
   "person":
   {
       "kind": "person",
       "id": 106,
       "name": "Galen Marek",
       "email": "marek@sith.mil",
       "initials": "GM",
       "username": "starkiller"
   },
   "project_color": "b800bb",
   "project_id": 99,
   "role": "member",
   "updated_at": "2016-10-18T12:00:00Z",
   "wants_comment_notification_emails": true,
   "will_receive_mention_notifications_or_emails": true
}]
```

## Todo
- [ ] Implement endpoint to query accounts
- [x] Implement Membership resource
- [x] Implement Person resource
- [ ] Implement integration test
