### ISSUE TITLE
Resource: Story Tasks

### ISSUE THREAD

**Issue by berfarah** [berfarah/pivotal.cr#4]
## Sample
```json
[
   {
       "kind": "task",
       "id": 5,
       "story_id": 559,
       "description": "Port 0",
       "complete": false,
       "position": 1,
       "created_at": "2016-10-18T12:00:00Z",
       "updated_at": "2016-10-18T12:00:00Z"
   },
   {
       "kind": "task",
       "id": 6,
       "story_id": 559,
       "description": "Port 90",
       "complete": false,
       "position": 2,
       "created_at": "2016-10-18T12:00:00Z",
       "updated_at": "2016-10-18T12:00:00Z"
   }
]
```

## Todo
- [ ] Implement endpoint to query tasks
- [ ] Implement Task resource
- [ ] Implement integration test
