### ISSUE TITLE
Resource: Story Labels

### ISSUE THREAD

**Issue by berfarah** [berfarah/pivotal.cr#5]
## Sample
```json
[
   {
       "kind": "label",
       "id": 2015,
       "project_id": 99,
       "name": "diplomatic relations",
       "created_at": 1476792000000,
       "updated_at": 1476792000000
   },
   {
       "kind": "label",
       "id": 2013,
       "project_id": 99,
       "name": "fleet ops",
       "created_at": 1476792000000,
       "updated_at": 1476792000000
   },
   {
       "kind": "label",
       "id": 2011,
       "project_id": 99,
       "name": "mnt",
       "created_at": 1476792000000,
       "updated_at": 1476792000000
   }
]
```

## Todo
- [ ] Implement endpoint to query labels
- [ ] Implement Label resource
- [ ] Implement integration test
