### ISSUE TITLE
Resource: Story Comments

### ISSUE THREAD

**Issue by berfarah** [berfarah/pivotal.cr#6]
## Sample
```json
[
   {
       "kind": "comment",
       "id": 111,
       "story_id": 555,
       "text": "I want them alive!",
       "person_id": 101,
       "created_at": "2016-10-18T12:00:00Z",
       "updated_at": "2016-10-18T12:00:00Z"
   }
]
```

## Todo
- [ ] Implement endpoint to query comments
- [ ] Implement Comment resource
- [ ] Implement integration test
