### ISSUE TITLE
Resource: Iteration

### ISSUE THREAD

**Issue by berfarah** [berfarah/pivotal.cr#7]
## Sample
```json
[
   {
       "number": 2,
       "project_id": 99,
       "length": 1,
       "team_strength": 1,
       "stories":
       [
           {
               "kind": "story",
               "id": 563,
               "created_at": "2016-10-18T12:01:00Z",
               "updated_at": "2016-10-18T12:01:00Z",
               "accepted_at": "2016-10-18T12:00:05Z",
               "estimate": 3,
               "story_type": "feature",
               "name": "Complete construction of the Expeditionary Battle Planetoid",
               "description": "Palpatine was impressed with the PoC, make this one bigger",
               "current_state": "accepted",
               "requested_by_id": 102,
               "external_id": "abc123",
               "integration_id": 30,
               "url": "http://localhost/story/show/563",
               "project_id": 99,
               "owner_ids":
               [
                   102,
                   101
               ],
               "labels":
               [
                   {
                       "id": 2009,
                       "project_id": 99,
                       "kind": "label",
                       "name": "plans",
                       "created_at": "2016-10-18T12:01:00Z",
                       "updated_at": "2016-10-18T12:01:00Z"
                   }
               ],
               "owned_by_id": 102
           }
       ],
       "start": "2016-10-18T12:01:00Z",
       "finish": "2016-10-18T12:00:10Z",
       "kind": "iteration"
   },
   {
       "number": 3,
       "project_id": 99,
       "length": 1,
       "team_strength": 1,
       "stories":
       [
       ],
       "start": "2016-10-18T12:00:10Z",
       "finish": "2016-10-18T12:00:15Z",
       "kind": "iteration"
   },
   {
       "number": 4,
       "project_id": 99,
       "length": 1,
       "team_strength": 1,
       "stories":
       [
       ],
       "start": "2016-10-18T12:00:15Z",
       "finish": "2016-10-18T12:00:20Z",
       "kind": "iteration"
   },
   {
       "number": 5,
       "project_id": 99,
       "length": 1,
       "team_strength": 1,
       "stories":
       [
       ],
       "start": "2016-10-18T12:00:20Z",
       "finish": "2016-10-18T12:00:25Z",
       "kind": "iteration"
   },
   {
       "number": 6,
       "project_id": 99,
       "length": 1,
       "team_strength": 1,
       "stories":
       [
       ],
       "start": "2016-10-18T12:00:25Z",
       "finish": "2016-10-18T12:00:30Z",
       "kind": "iteration"
   },
   {
       "number": 7,
       "project_id": 99,
       "length": 1,
       "team_strength": 1,
       "stories":
       [
       ],
       "start": "2016-10-18T12:00:30Z",
       "finish": "2016-10-18T12:00:35Z",
       "kind": "iteration"
   },
   {
       "number": 8,
       "project_id": 99,
       "length": 1,
       "team_strength": 1,
       "stories":
       [
       ],
       "start": "2016-10-18T12:00:35Z",
       "finish": "2016-10-18T12:00:40Z",
       "kind": "iteration"
   },
   {
       "number": 9,
       "project_id": 99,
       "length": 1,
       "team_strength": 1,
       "stories":
       [
       ],
       "start": "2016-10-18T12:00:40Z",
       "finish": "2016-10-18T12:00:45Z",
       "kind": "iteration"
   },
   {
       "number": 10,
       "project_id": 99,
       "length": 1,
       "team_strength": 1,
       "stories":
       [
       ],
       "start": "2016-10-18T12:00:45Z",
       "finish": "2016-10-18T12:00:50Z",
       "kind": "iteration"
   },
   {
       "number": 11,
       "project_id": 99,
       "length": 1,
       "team_strength": 1,
       "stories":
       [
       ],
       "start": "2016-10-18T12:00:50Z",
       "finish": "2016-10-18T12:00:55Z",
       "kind": "iteration"
   }
]
```

## Todo
- [x] Implement endpoint on project to query Iteration
- [x] Implement Iteration resource
- [x] Implement integration test
