### ISSUE TITLE
Update README.md with usage examples

### ISSUE THREAD

**Issue by berfarah** [berfarah/pivotal.cr#9]
## Todo
1. [ ] Show how you would authenticate
2. [ ] Give an example where you know your token
3. [ ] Write a list of available resources via this client
4. [ ] Put together extensive example involving projects, stories and labels
